apiVersion: apps/v1
kind: Deployment
metadata:
  name: aha-backend-deployment
  labels:
    app: aha-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aha-backend
  template:
    metadata:
      labels:
        app: aha-backend
    spec:
      containers:
      - name: aha-backend
        image: docker.io/lakshmi7330/aha-backend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: MONGO_URI
          value: "mongodb://reddycloud910_db_user:gu1jDcwQMObo0aoC@cluster0-shard-00-00.l99lok8.mongodb.net:27017/netflixClone?ssl=true&authSource=admin&retryWrites=true&w=majority"
        - name: JWT_SECRET
          value: "mySuperSecretNetflixCloneKey2026!@#"
        - name: VITE_API_URL
          value: "http://localhost:5000"
---
apiVersion: v1
kind: Service
metadata:
  name: aha-backend
spec:
  type: ClusterIP # Exposes backend internally inside the cluster network
  selector:
    app: aha-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aha-frontend-deployment
  labels:
    app: aha-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aha-frontend
  template:
    metadata:
      labels:
        app: aha-frontend
    spec:
      containers:
      - name: aha-frontend
        image: docker.io/lakshmi7330/aha-frontend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aha-frontend
spec:
  type: LoadBalancer # Exposes frontend outside the cluster to your browser
  selector:
    app: aha-frontend
  ports:
    - protocol: TCP
      port: 3000       # Type http://localhost:3000 in your browser
      targetPort: 80   # Routes to Nginx inside the frontend container
