apiVersion: v1
kind: Secret
metadata:
  name: aha-backend-secrets
type: Opaque
stringData:
  MONGO_URI: "mongodb://reddycloud910_db_user:<password>@cluster0-shard-00-00.l99lok8.mongodb.net:27017/netflixClone?ssl=true&authSource=admin&retryWrites=true&w=majority"
  JWT_SECRET: "mySuperSecretNetflixCloneKey2026!@#"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aha-backend-deployment
  labels:
    app: aha-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aha-backend
  template:
    metadata:
      labels:
        app: aha-backend
    spec:
      containers:
      - name: aha-backend
        image: docker.io/lakshmi7330/aha-backend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
        env:
        - name: PORT
          value: "5000"
        - name: VITE_API_URL
          value: "http://aha-backend:5000"   
        - name: MONGO_URI
          valueFrom:
            secretKeyRef:
              name: aha-backend-secrets
              key: MONGO_URI
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: aha-backend-secrets
              key: JWT_SECRET
        resources:
          requests:
            cpu: "250m"
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
----------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: aha-backend
spec:
  type: ClusterIP
  selector:
    app: aha-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
----------------------------------------------------------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aha-frontend-deployment
  labels:
    app: aha-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: aha-frontend
  template:
    metadata:
      labels:
        app: aha-frontend
    spec:
      containers:
      - name: aha-frontend
        image: docker.io/lakshmi7330/aha-frontend:1.0.1
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 15
--------------------------------------------------------------------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: aha-frontend
spec:
  type: LoadBalancer
  selector:
    app: aha-frontend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 80
